blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls'))
]

home/urls.py
from django.conf.urls import url,include

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^blogs/$', views.blog_view, name='blog_page'),
]

home/models.py
from django.db import models

# Create your models here.
class BlogEntries(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    title = models.CharField(max_length=100)
    post = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

home/forms.py
from django import forms
from .models import BlogEntries

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogEntries
        fields = '__all__'
        widgets = {
            "post": forms.Textarea(attrs={
                "style": "resize:none;",
                "cols": "10",
                "rows": "7"})}

home/views.py
from django.shortcuts import render
from .forms import BlogForm
from .models import BlogEntries
# Create your views here.

def blog_view(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        form.save()
    if request.method == 'GET':
        form = BlogForm()
    context = BlogEntries.objects.all()
    return render(request, 'home/blog.html', {'form': form,'context':context})

home/templates/home/blog.html
{% load crispy_forms_tags %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="well" style="margin: 0% 10% 10% 10%;">
    <h2 class="text-center" style="letter-spacing: 6px; font-weight: bolder; padding-bottom: 3vh;">BLOG POSTS</h2>
    {% for blog in context %}
        <div class="well panel panel-default" style="background-color: white; box-shadow: 2px 2px 16px 0px rgba(0,0,0,0.4); padding: 5vh 8vw;
">
            <div class="panel-heading" style="background-color: white;"><h4 style="font-weight: bold;">{{ blog.title }}</h4>
        <h5 style="color: #999;">{{ blog.timestamp|naturaltime }}</h5>
        <h5>Author-{{blog.name}}</h5>
                </div>
            <div class="panel-body" style="text-align:justify; padding: 2vh 3vw;"><h5>{{ blog.post }}</h5></div>
        </div>

    {% endfor %}

<div style="padding: 5% 50% 0% 0% ; >
    <form action="{% url 'home:blog_page' %}" method="post" style="background-color: white; padding: 4vh 2vw; box-shadow: 2px 2px 16px 0px rgba(0,0,0,0.3);">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary btn-block" value="Submit" />
    </form>
</div>
</div>
</body>
</html>